redis:
  image:
    repository: redis
    tag: 6.2.6
    pullPolicy: IfNotPresent

  password: devredis123

  service:
    type: ClusterIP
    port: 6379

  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"

  configInline: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    appendonly yes
    save 60 1000

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
