redis:
  name: redis
  image: redis:7.2
  port: 6379
  replicas: 1

  config:
    maxmemory: "256mb"
    policy: "allkeys-lru"

  auth:
    enabled: true
    password: "changeme123"

  persistence:
    enabled: true
    size: 1Gi
