redis-backend:
  redis:
    name: redis-backend
    replicas: 1

    image:
      repository: redis
      tag: "7.2.4"
      pullPolicy: IfNotPresent

    port: 6379

    terminationGracePeriodSeconds: 10
    updateStrategy: RollingUpdate

    service:
      name: redis-backend-service
      type: ClusterIP
      headless: false
      ports:
        - name: redis
          port: 6379
          targetPort: 6379

    configMap:
      name: redis-backend-config

    auth:
      enabled: true
      secret:
        name: redis-backend-secret
        password: "supersecurepassword"

    config:
      bind: "0.0.0.0"
      maxmemory: "256mb"
      policy: "allkeys-lru"

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    containerSecurityContext:
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    persistence:
      enabled: true
      size: 1Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: ""

    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
