apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    password: {{ .Values.password | b64enc }}
  template:
    metadata:
      name: {{ .Release.Name }}-redis-secret
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
    type: Opaque
