apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | b64enc | quote }}
