apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  serviceName: {{ .Release.Name }}-redis
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis-secret
                  key: redis-password
          volumeMounts:
            - name: redis-data
              mountPath: /data
              subPath: data
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
              readOnly: true
          livenessProbe:
            exec:
              command: ["sh", "-c", "redis-cli -a $REDIS_PASSWORD ping || exit 1"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ["sh", "-c", "redis-cli -a $REDIS_PASSWORD ping || exit 1"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory | quote }}
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory | quote }}
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
      volumes:
        - name: redis-config
          secret:
            secretName: {{ .Release.Name }}-redis-config-secret
        {{- if not .Values.redis.persistence.enabled }}
        - name: redis-data
          emptyDir: {}
        {{- end }}
{{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
{{- end }}
