{{- define "redis-template.secret" }}
{{- if .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.secret.name }}
  labels:
    app: {{ .Values.redis.name }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc }}
{{- end }}
{{- end }}
